spring:
  datasource:
    url: jdbc:mysql://localhost:3306/innkyblog
    username: root
    password: "000508"
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml  #sql映射文件位置
  type-aliases-package: xyz.innky.bootproj.pojo
server:
  port: 8081
#  ssl:
#    enabled: true
#    # keystore 文件
#    key-store: classpath:www.innky.xyz.keystore
#    key-store-type: PKCS12
#    # keystore的密码
#    key-store-password: 123456
logging:
  level:
    xyz.innky.bootproj: DEBUG