spring:
  datasource:
    url: jdbc:mysql://localhost:3306/innkyblog
    username: root
    password: "000508"

server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml  #sql映射文件位置
  type-aliases-package: xyz.innky.bootproj.pojo